version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - online_courses_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=online_courses_user
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=online_courses_db
    ports:
      - "5432:5432"
    networks:
      - online_courses_network

volumes:
  postgres_data:

networks:
  online_courses_network:
    driver: bridge